# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


user_one = User.create(username: "James", password: "1234")
user_two = User.create(username: "Jason", password: "1234")

game_one = Game.create(title: "Dunwich Legacy", user_id: 1)
game_two = Game.create(title: "The Path to Carcosa", user_id: 2)

scenario_one = Scenario.create(name: "Blood on the Altar", game_id: 1)
scenario_two = Scenario.create(name: "Echoes of the Past", game_id: 2)

character_base_pete = CharacterBase.create(name: "Ashcan Pete", title: "The Drifter", health: 6, sanity: 5, willpower: 4, intellect: 2, combat: 2, agility: 2, category: "Survivor")
character_base_skids = CharacterBase.create(name: "Skids O'Toole", title: "The Ex-con", health: 8, sanity: 6, willpower: 2, intellect: 3, combat: 3, agility: 4, category: "Rogue")
character_base_agnes = CharacterBase.create(name: "Agnes Baker", title: "The Waitress", health: 6, sanity: 8, willpower: 5, intellect: 2, combat: 2, agility: 3, category: "Mystic")
character_base_akachi = CharacterBase.create(name: "Akachi Onyele", title: "The Shaman", health: 6, sanity: 8, willpower: 5, intellect: 2, combat: 3, agility: 3, category: "Mystic")
character_base_amanda = CharacterBase.create(name: "Amanda Sharpe", title: "The Student", health: 7, sanity: 7, willpower: 2, intellect: 2, combat: 2, agility: 2, category: "Seeker")
character_base_calvin = CharacterBase.create(name: "Calvin Wright", title: "The Haunted", health: 6, sanity: 6, willpower: 0, intellect: 0, combat: 0, agility: 0, category: "Survivor")
character_base_carolyn = CharacterBase.create(name: "Carolyn Fern", title: "The Psychologist", health: 6, sanity: 9, willpower: 3, intellect: 4, combat: 2, agility: 2, category: "Guardian")
character_base_daisy = CharacterBase.create(name: "Daisy Ealker", title: "The Librarian", health: 5, sanity: 9, willpower: 3, intellect: 5, combat: 2, agility: 2, category: "Seeker")
character_base_dexter = CharacterBase.create(name: "Dexter Drake", title: "The Magician", health: 6, sanity: 8, willpower: 5, intellect: 2, combat: 3, agility: 2, category: "Mystic")
character_base_diana = CharacterBase.create(name: "Diana Stanley", title: "The Redeemed Cultist", health: 7, sanity: 7, willpower: 1, intellect: 3, combat: 3, agility: 3, category: "Mystic")
character_base_mateo = CharacterBase.create(name: "Father Mateo", title: "The Priest", health: 6, sanity: 8, willpower: 4, intellect: 3, combat: 2, agility: 3, category: "Mystic")
character_base_finn = CharacterBase.create(name: "Finn Edwards", title: "The Bootlegger", health: 7, sanity: 7, willpower: 1, intellect: 4, combat: 3, agility: 4, category: "Rogue")
character_base_gloria = CharacterBase.create(name: "Gloria Goldberg", title: "The Writer", health: 5, sanity: 9, willpower: 5, intellect: 4, combat: 2, agility: 1, category: "Mystic")
character_base_harvey = CharacterBase.create(name: "Harvey Walters", title: "The Professor", health: 7, sanity: 8, willpower: 4, intellect: 5, combat: 1, agility: 2, category: "Seeker")
character_base_jacqueline = CharacterBase.create(name: "Jacquline Fine", title: "The Psychic", health: 6, sanity: 9, willpower: 5, intellect: 3, combat: 2, agility: 2, category: "Mystic")
character_base_jenny = CharacterBase.create(name: "Jenny Barnes", title: "The Dilettante", health: 8, sanity: 7, willpower: 3, intellect: 3, combat: 3, agility: 3, category: "Rogue")
character_base_jim = CharacterBase.create(name: "Jim Culver", title: "The Musician", health: 7, sanity: 8, willpower: 4, intellect: 3, combat: 3, agility: 2, category: "Mystic")
character_base_joe = CharacterBase.create(name: "Joe Diamond", title: "The Private Investigator", health: 8, sanity: 6, willpower: 2, intellect: 4, combat: 4, agility: 2, category: "Seeker")
character_base_leo = CharacterBase.create(name: "Leo Anderson", title: "The Expedition Leader", health: 8, sanity: 6, willpower: 4, intellect: 3, combat: 4, agility: 1, category: "Guardian")
character_base_lola = CharacterBase.create(name: "Lola Hayes", title: "The Actress", health: 6, sanity: 6, willpower: 3, intellect: 3, combat: 3, agility: 3, category: "Neutral")
character_base_luke = CharacterBase.create(name: "Luke Robinson", title: "The Dreamer", health: 5, sanity: 9, willpower: 4, intellect: 3, combat: 2, agility: 3, category: "Mystic")
character_base_mandy = CharacterBase.create(name: "Mandy Thompson", title: "The Researcher", health: 6, sanity: 8, willpower: 3, intellect: 5, combat: 1, agility: 3, category: "Seeker")
character_base_marie = CharacterBase.create(name: "Marie Lambeau", title: "The Entertainer", health: 6, sanity: 8, willpower: 4, intellect: 4, combat: 1, agility: 3, category: "Mystic")
character_base_mark = CharacterBase.create(name: "Mark Harrigan", title: "The Soldier", health: 9, sanity: 5, willpower: 3, intellect: 2, combat: 5, agility: 3, category: "Guardian")
character_base_minh = CharacterBase.create(name: "Minh Thi Phan", title: "The Secretary", health: 7, sanity: 7, willpower: 4, intellect: 4, combat: 2, agility: 2, category: "Seeker")
character_base_nathaniel = CharacterBase.create(name: "Nathaniel Cho", title: "The Boxer", health: 9, sanity: 6, willpower: 3, intellect: 2, combat: 5, agility: 2, category: "Guardian")
character_base_norman = CharacterBase.create(name: "Norman Withers", title: "The Astronomer", health: 6, sanity: 8, willpower: 4, intellect: 5, combat: 2, agility: 1, category: "Seeker")
character_base_patrice = CharacterBase.create(name: "Patrice Hathaway", title: "The Violinist", health: 7, sanity: 7, willpower: 4, intellect: 2, combat: 2, agility: 2, category: "Survivor")
character_base_preston = CharacterBase.create(name: "Preston Fairmont", title: "The Millionaire", health: 7, sanity: 7, willpower: 1, intellect: 1, combat: 1, agility: 1, category: "Rogue")
character_base_rex = CharacterBase.create(name: "Rex Murphy", title: "The Reporter", health: 6, sanity: 9, willpower: 3, intellect: 4, combat: 2, agility: 3, category: "Seeker")
character_base_rita = CharacterBase.create(name: "Rita Young", title: "The Athlete", health: 9, sanity: 5, willpower: 3, intellect: 2, combat: 3, agility: 5, category: "Survior")
character_base_roland = CharacterBase.create(name: "Roland Banks", title: "The Fed", health: 9, sanity: 5, willpower: 3, intellect: 3, combat: 4, agility: 2, category: "Guardian")
character_base_sefina = CharacterBase.create(name: "Sefina Rousseau", title: "The Painter", health: 5, sanity: 9, willpower: 4, intellect: 2, combat: 2, agility: 4, category: "Rogue")
character_base_silas = CharacterBase.create(name: "Silas Marsh", title: "The Sailor", health: 9, sanity: 5, willpower: 2, intellect: 2, combat: 4, agility: 4, category: "Survior")
character_base_mary = CharacterBase.create(name: "Sister Mary", title: "The Nun", health: 5, sanity: 9, willpower: 4, intellect: 2, combat: 3, agility: 3, category: "Guardian")
character_base_stella = CharacterBase.create(name: "Stella Clark", title: "The Letter Carrier", health: 8, sanity: 8, willpower: 3, intellect: 2, combat: 3, agility: 4, category: "Survior")
character_base_tommy = CharacterBase.create(name: "Tommy Muldoon", title: "The Rookie Cop", health: 8, sanity: 6, willpower: 3, intellect: 6, combat: 4, agility: 2, category: "Guardian")
character_base_tony = CharacterBase.create(name: "Tony Morgan", title: "The Bounty Hunter", health: 9, sanity: 5, willpower: 2, intellect: 3, combat: 5, agility: 2, category: "Rogue")
character_base_trish = CharacterBase.create(name: "Trish Scarborough", title: "The Spy", health: 8, sanity: 6, willpower: 2, intellect: 4, combat: 2, agility: 4, category: "Rogue")
character_base_ursula = CharacterBase.create(name: "Ursula Downs", title: "The Explorer", health: 7, sanity: 7, willpower: 3, intellect: 4, combat: 1, agility: 4, category: "Seeker")
character_base_wendy = CharacterBase.create(name: "Wendy Adams", title: "The Urchin", health: 7, sanity: 7, willpower: 4, intellect: 3, combat: 1, agility: 4, category: "Survior")
character_base_william = CharacterBase.create(name: "William Yorick", title: "The Gravedigger", health: 8, sanity: 6, willpower: 3, intellect: 2, combat: 4, agility: 3, category: "Survior")
character_base_winifred = CharacterBase.create(name: "Winifred Habbamock", title: "The Aviatrix", health: 8, sanity: 7, willpower: 1, intellect: 3, combat: 3, agility: 5, category: "Rogue")
character_base_zoey = CharacterBase.create(name: "Zoey Samaras", title: "The Chef", health: 9, sanity: 6, willpower: 4, intellect: 2, combat: 4, agility: 2, category: "Guardian")